### PR TITLE
Fix crash in ContainerSellValue

### PR DESCRIPTION
**Pull request by lineargraph**

### CODE REVIEW

**Comment by lineargraph** [comment]
Hi @My-Name-Is-Jeff any updates on this?

**Comment by My-Name-Is-Jeff** [comment]
Can't repro

**Comment by lineargraph** [comment]
I mean i could, and so could like everyone in our support channels i gave this to. And either way this isnt exactly like it would be worse to do this way either.

**Comment by lineargraph** [comment]
It's nicer code in it's own right, it fixes a bug, and you *already* have a hacky solution that you needed to do because of NEUs storage gui, so why not try to be fully compatible with NEU.

**Pull request closed without merging**
