### PR TITLE
Add a RAT to Skytils!

### PR DESCRIPTION
**Pull request by AfkUserMC**

### CODE REVIEW

**Comment by My-Name-Is-Jeff** [comment]
Congrats, you just earned yourself a permanent block

**Comment by Advik-B** [comment]
But you still added it ¯\_(ツ)_/¯

**Comment by Sychic** [comment]
There's a difference. Assuming you're here from the [twitter post by azure](https://x.com/possiblyazure/status/1792524230518526113), that's implemented differently. This pr is simply a picture of a rat which does nothing at all and wastes ~800KB of space.

**Comment by Advik-B** [comment]
> There's a difference. Assuming you're here from the [twitter post by azure](https://x.com/possiblyazure/status/1792524230518526113), that's implemented differently. This pr is simply a picture of a rat which does nothing at all and wastes ~800KB of space.

Yea I actually searched thru the code to find the impl of it, not just the picture

**Pull request closed without merging**
