### PR TITLE
Fixed Close Button

### PR DESCRIPTION
**Pull request by TakoTheDev**
I hope this is fine, idk why it works this way, but it does

### CODE REVIEW

**Review by Sychic — COMMENTED** [review]
How does this actually do anything? seems like it does the exact same thing as before?

**Comment by My-Name-Is-Jeff** [comment]
> How does this actually do anything? seems like it does the exact same thing as before?

I think both are on different class loaders

**Comment by TakoTheDev** [comment]
> How does this actually do anything? seems like it does the exact same thing as before?

Like idk either, but it works somehow

**Comment by TakoTheDev** [comment]
> > How does this actually do anything? seems like it does the exact same thing as before?
> 
> I think both are on different class loaders

yea seems to be the case, at least to my knowledge

**Pull request merged**
