### PR TITLE
Add farming features: Click screen to accept Trapper task and Trapper cooldown alarm

### PR DESCRIPTION
**Pull request by Quantizr**
Definitely didn't just take a bit of DSM code and modify it... 
(dw, I gave attribution)

Idk what the policy is on adding keybinds into controls, and idk how to add a keybind option into the modcore gui. Because of this, there isn't a keybind to accept the task

image

### CODE REVIEW

**Comment by Quantizr** [comment]
Also added a Trapper Cooldown Alarm, which plays note.pling 5 times in a row when the 1 minute cooldown is up if the animal has already been found

**Comment by CedricL1u** [comment]
The griffin burrow doesn't work for some reason 
image
It says this endpoint is currently disabled

**Comment by Quantizr** [comment]
> The griffin burrow doesn't work for some reason
> image
> It says this endpoint is currently disabled

Idk if you can read but the issue is well documented across the Skytils Discord and the Hypixel forums. Second, you commented on a pull request and I'm not a Skytils developer... I have no idea what you're trying to do


Anyway actual pull request moved to Kotlin #14

**Comment by CedricL1u** [comment]
idk how to use github I just came there since my griffin waypoints didn't
work

**Pull request closed without merging**
