### PR TITLE
improved crystal hollows map

### PR DESCRIPTION
**Pull request by DeDiamondPro**
- larger square for player because it was almost not visible
- add something on map to display where a special zone is using the data in the scoreboard and the min and max that the player has been inside this zone to make it accurate
- added waypoints to special zones
- added something to grab coordinates from in chat when the player click which one of the special locations it is
- added config options
Screenshots:
image
image
image
image

### CODE REVIEW

**Comment by DeDiamondPro** [comment]
bruh 2/3 complex code issues aren't even created by the new code and the one which is isn't even that complex, I really don't know what I need to do to make CodeFactor happy

**Comment by DeDiamondPro** [comment]
I'm 90% sure I'm done now but since I'm playing a bit on alpha I might come up with something else, if I need to change anything just tell me

**Comment by My-Name-Is-Jeff** [comment]
Might need to remake the Map graphic before merging

**Comment by DeDiamondPro** [comment]
> Might need to remake the Map graphic before merging

I agree, if you give me some time I can redo the map a bit with the data from forum post https://hypixel.net/threads/guide-crystal-hollows-locations-layout-completed.4372625/

**Comment by DeDiamondPro** [comment]
Lily epic map in support channel but the nucleus prob needs to be a bit bigger, it goes from  about (460,460) to (560, 560)

**Comment by My-Name-Is-Jeff** [comment]
> Lily epic map in support channel but the nucleus prob needs to be a bit bigger, it goes from about (460,460) to (560, 560)

tested it and it seems just right

**Review by Sychic — APPROVED** [review]
lgtm

**Pull request merged**
